# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Typescript CDK deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4

    - name: Install web app dependencies
      working-directory: ./web
      run: npm ci

    - name: Build Web app
      working-directory: ./web
      run: npm run build

    - name: Install AWS CDK 
      run: sudo npm i -g aws-cdk

    - name: Install Deployment dependencies 
      working-directory: ./ts-webdeployment
      run: sudo npm i 

    - name: Synth CDK 
      working-directory: ./ts-webdeployment
      run: cdk-synth

    - name: Deploy CDK
      working-directory: ./ts-webdeployment
      env :
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
        AWS_DEFAULT_REGION: ${{ secrets. AWS_DEFAULT_REGION }}
      run: cdk-deploy
    
